config_version: 1.0.0
webserver:
    port: 8181
    allowed_domains:
    - http://localhost:3000
mariadb:
    url: jdbc:mariadb://mariadb:3306/vault
    user: root
    password: password
uploads:
    mount_point: ./uploads
    max_size: 5.0E7
pfp:
    mount_point: ./pfps
